const animals = ["GATO", "ABELHA", "ABUTRE", "AGUIA", "ALBATROZ", "ALCE", "ALPACA", "ANTA", "ARANHA", "ARARA", "ARARAJUBA", "ARIRANHA", "ATUM", "BABEJO", "BAGRE", "BALEIA", "BELUGA", "BESOURO", "BODE", "BOI", "BORBOLETA", "BUFALO", "BURRO", "CABRA", "CACATUA", "CACHORRO", "CALANGO", "CAMELO", "CAMUNDONGO", "CANGURU", "CAPIVARA", "CARACOL", "CARAMUJO", "CARANGUEJO", "CARNEIRO", "CARRAPATO", "CAVALO", "CEGONHA", "CENTOPEIA", "CHACAL", "CIGARRA", "COELHO", "CORUJA", "CROCODILO", "CUPIM", "CUTIA", "DONINHA", "DUGONGO", "ELEFANTE", "EMA", "ENGUIA", "ESPONJA", "ESQUILO", "FLAMINGO", "FOCA", "FORMIGA", "FUINHA", "GAFANHOTO", "GAIVOTA", "GALO", "GAMO", "GANSO", "GARÇA", "GAVIAL", "GAZELA", "GIRAFA", "GNU", "GOLFINHO", "GORILA", "GRALHA", "GRILO", "GUEPARDO", "HADOQUE", "HAMSTER", "HIENA", "IGUANA", "IMPALA", "IRARA", "JABOTI", "JACUTINGA", "JAGUATIRICA", "JAMANTA", "JARARACA", "JAVALI", "JIBOIA", "JOANINHA", "JUMENTO", "KAKAPO", "KINGUIO", "KOWARI", "KRILL", "LACRAIA", "LAGARTO", "LAGARTIXA", "LAGOSTA", "LAGOSTIM", "LEBRE", "LEOPARDO", "LESMA", "LHAMA", "LINCE", "LOBO", "LONTRA", "LULA", "MACACO", "MAMUTE", "MANGUSTO", "MARIPOSA", "MARMOTA", "MARRECO", "MORSA", "MOSCA", "MOSQUITO", "MULA", "NOIVINHA", "NARVAL", "NIQUIM", "ONÇA", "ORANGOTANGO", "ORCA", "OSTRA", "OURIÇO", "OVELHA", "PACA", "PANDA", "PATO", "PINTO", "PUMA", "QUATI", "RATO", "RAPOSA", "RENA", "SAGUI", "SALAMANDRA", "SAPO", "SARDINHA", "SIRI", "TAINHA", "TARTARUGA", "TATU", "TIGRE", "TOURO", "URSO", "URUBU", "URUMUTUM", "VACA", "XIMANGO", "ZEBRA", "ZEBU", "ZAGLOSSO", "XIMANGO", "WALLABY"];

animals.sort((a, b) => {
    return a.localeCompare(b);
});

const countries = ["SENEGAL", "AFRICA", "ALEMANHA", "ANGOLA", "ALBANIA", "ARGELIA", "ARGENTINA", "AUSTRALIA", "BAHAMAS", "BARBADOS", "BELGICA", "BOLIVIA", "BRASIL", "BULGARIA", "CHILE", "CHIPRE", "COLOMBIA", "COREIA", "CROACIA", "CUAITE", "DINAMARCA", "EGITO", "EQUADOR", "ESPANHA", "FINLANDIA", "GANA", "GRECIA", "HAITI", "HONDURAS", "INDIA", "ITALIA", "JAMAICA", "MALDIVAS", "MEXICO", "PANAMA", "PERU", "POLONIA", "PORTUGAL", "UCRANIA", "VIETNA"];

countries.sort((a, b) => {
    return a.localeCompare(b);
});

const fruits = ["UMBU", "ABACATE", "ABACAXI", "ACEROLA", "AMEIXA", "AMORA", "BABAÇU", "BACURI", "BANANA", "BERGAMOTA", "CACAU", "CAJU", "CAQUI", "COCO", "CRANBERRY", "DAMASCO", "ENGKALA", "FIGO", "FRAMBOESA", "GOIABA", "GRAVIOLA", "GUARANÁ", "IMBU", "JABOTICABA", "JACA", "JAMBO", "KIWI", "LARANJA", "LANGSAT", "MAMAO", "MARACUJA", "MELAO", "MEXERICA", "MORANGO", "NOZ", "OITI", "PERA", "PITANGA", "PEQUI", "SAPOTI", "TANGERINA", "UVA", "ZIMBRO"];

fruits.sort((a, b) => {
    return a.localeCompare(b);
});

const objects = ["LATA", "ALICATE", "AGULHA", "ADAGA", "ANEL", "ANTENA", "ARCO", "ASPIRADOR", "BACIA", "BALANÇA", "BANCO", "BATOM", "BENGALA", "BEXIGA", "CABIDE", "CADEADO", "CADEIRA", "CADERNO", "CAJADO", "CALÇA", "CAMISA", "CANETA", "CANIVETE", "CAPA", "CASTIÇAL", "CD", "CELULAR", "CHAVE", "CHICOTE", "CHUPETA", "CLIPE", "COLAR", "COLHER", "DADO", "DARDO", "DENTADURA", "DESFIBRILADOR", "DESPERTADOR", "DETERGENTE", "DVD", "DINAMITE", "ENVELOPE", "ESCOVA", "ESCUDO", "ESMALTE", "ESPADA", "ESPELHO", "ESPONJA", "EXTINTOR", "FACA", "FAX", "FUNIL", "FURADEIRA", "FLECHA", "GAIOLA", "GAITA", "GANCHO", "GARFO", "GARRAFA", "GORRO", "GRAMOFONE", "GRAMPO", "GUITARRA", "HALTERE", "HARPA", "IMPRESSORA", "INALADOR", "INCENSO", "INGRESSO", "ISCA", "JALECO", "JANELA", "JAQUETA", "KART", "KIT", "LAPIS", "LEME", "LUVA", "LOUSA", "LIXO", "LUNETA", "LIQUIDIFICADOR", "LIVRO", "NAVE", "NAVIO", "NOTEBOOK", "OCULOS", "PENTE", "PIANO", "PICARETA", "PINÇA", "PISTOLA", "PLACA", "POTE", "QUADRO", "QUEPE", "RALO", "REDE", "SABONETE", "SACO", "TAMPA", "TECLADO", "TELEFONE", "UNIFORME", "UKULELE", "WALKMAN", "WEBCAM", "XADREZ", "XILOFONE", "ZABUMBA"];

objects.sort((a, b) => {
    return a.localeCompare(b);
});

// let letra = "Ô";
// let letra2 = "O";

// if (letra.normalize("NFD").replace(/[\u0300-\u036f]/g, "") === letra2.normalize("NFD").replace(/[\u0300-\u036f]/g, "")) {
//     console.log("iguais");
// } else {
//     console.log("diferente");
// }