const animals = ["GATO", "ABELHA", "ABUTRE", "ÁGUIA", "ALBATROZ", "ALCE", "ALPACA", "ANTA", "ARANHA", "ARARA", "ARARAJUBA", "ARIRANHA", "ATUM", "BADEJO", "BAGRE", "BALEIA", "BELUGA", "BESOURO", "BODE", "BOI", "BORBOLETA", "BÚFALO", "BURRO", "CABRA", "CACATUA", "CACHORRO", "CALANGO", "CAMELO", "CAMUNDONGO", "CANGURU", "CAPIVARA", "CARACOL", "CARAMUJO", "CARANGUEJO", "CARNEIRO", "CARRAPATO", "CAVALO", "CEGONHA", "CENTOPEIA", "CHACAL", "CIGARRA", "COELHO", "CORUJA", "CROCODILO", "CUPIM", "CUTIA", "DONINHA", "DUGONGO", "ELEFANTE", "EMA", "ENGUIA", "ESPONJA", "ESQUILO", "FLAMINGO", "FOCA", "FORMIGA", "FUINHA", "GAFANHOTO", "GAIVOTA", "GALO", "GAMO", "GANSO", "GARÇA", "GAVIAL", "GAZELA", "GIRAFA", "GNU", "GOLFINHO", "GORILA", "GRALHA", "GRILO", "GUEPARDO", "HADOQUE", "HAMSTER", "HIENA", "IGUANA", "IMPALA", "IRARA", "JABOTI", "JACUTINGA", "JAGUATIRICA", "JAMANTA", "JARARACA", "JAVALI", "JIBOIA", "JOANINHA", "JUMENTO", "KAKAPO", "KINGUIO", "KOWARI", "KRILL", "LACRAIA", "LAGARTO", "LAGARTIXA", "LAGOSTA", "LAGOSTIM", "LEÃO", "LEBRE", "LEOPARDO", "LESMA", "LHAMA", "LINCE", "LOBO", "LONTRA", "LULA", "MACACO", "MAMUTE", "MANGUSTO", "MARIPOSA", "MARMOTA", "MARRECO", "MORSA", "MOSCA", "MOSQUITO", "MULA", "NOIVINHA", "NARVAL", "NIQUIM", "ONÇA", "ORANGOTANGO", "ORCA", "OSTRA", "OURIÇO", "OVELHA", "PACA", "PANDA", "PATO", "PINTO", "PUMA", "QUATI", "RATO", "RAPOSA", "RENA", "SAGUI", "SALAMANDRA", "SAPO", "SARDINHA", "SIRI", "TAINHA", "TARTARUGA", "TATU", "TIGRE", "TOURO", "URSO", "URUBU", "URUMUTUM", "VACA", "XIMANGO", "ZEBRA", "ZEBU", "ZAGLOSSO", "XIMANGO", "WALLABY", "JACARÉ", "SABIÁ", "ANTÍLOPE", "TAMANDUÁ"];

animals.sort((a, b) => {
    return a.localeCompare(b);
});

const countries = ["SENEGAL", "AFRICA", "ALEMANHA", "ANGOLA", "ALBÂNIA", "ARGÉLIA", "ARGENTINA", "AUSTRÁLIA", "BAHAMAS", "BARBADOS", "BÉLGICA", "BOLÍVIA", "BRASIL", "BULGÁRIA", "CHILE", "CHIPRE", "COLÔMBIA", "COREIA", "CROÁCIA", "KUWAIT", "DINAMARCA", "EGITO", "EQUADOR", "ESPANHA", "FINLÂNDIA", "GANA", "GRÉCIA", "HAITI", "HONDURAS", "ÍNDIA", "ITÁLIA", "JAMAICA", "MALDIVAS", "MÉXICO", "PANAMÁ", "PERU", "POLÔNIA", "PORTUGAL", "UCRÂNIA", "VIETNÃ", "AFEGANISTÃO", "ÁUSTRIA", "CANADÁ", "ESLOVÁQUIA", "ESLOVÊNIA", "FRANÇA", "GUINÉ", "MALÁSIA"];

countries.sort((a, b) => {
    return a.localeCompare(b);
});

const fruits = ["UMBU", "ABACATE", "ABACAXI", "ACEROLA", "AMEIXA", "AMORA", "BABAÇU", "BACURI", "BANANA", "BERGAMOTA", "CACAU", "CAJU", "CAQUI", "COCO", "CRANBERRY", "DAMASCO", "ENGKALA", "FIGO", "FRAMBOESA", "GOIABA", "GRAVIOLA", "GUARANÁ", "IMBU", "JABOTICABA", "JACA", "JAMBO", "KIWI", "LARANJA", "LANGSAT", "MAMÃO", "MARACUJÁ", "MELÃO", "MEXERICA", "MORANGO", "NOZ", "OITI", "PERA", "PITANGA", "PEQUI", "SAPOTI", "TANGERINA", "UVA", "ZIMBRO", "AÇAÍ", "ARAÇÁ", "AVELÃ", "BUTIÁ", "CAJÁ", "CAMBUCÁ", "DENDÊ", "INGÁ", "LIMÃO", "MAÇÃ", "ROMÃ", "YUZU"];

fruits.sort((a, b) => {
    return a.localeCompare(b);
});

const objects = ["LATA", "ALICATE", "AGULHA", "ADAGA", "ANEL", "ANTENA", "ARCO", "ASPIRADOR", "BACIA", "BALANÇA", "BANCO", "BATOM", "BENGALA", "BEXIGA", "CABIDE", "CADEADO", "CADEIRA", "CADERNO", "CAJADO", "CALÇA", "CAMISA", "CANETA", "CANIVETE", "CAPA", "CASTIÇAL", "CD", "CELULAR", "CHAVE", "CHICOTE", "CHUPETA", "CLIPE", "COLAR", "COLHER", "DADO", "DARDO", "DENTADURA", "DESFIBRILADOR", "DESPERTADOR", "DETERGENTE", "DVD", "DINAMITE", "ENVELOPE", "ESCOVA", "ESCUDO", "ESMALTE", "ESPADA", "ESPELHO", "ESPONJA", "EXTINTOR", "FACA", "FAX", "FUNIL", "FURADEIRA", "FLECHA", "GAIOLA", "GAITA", "GANCHO", "GARFO", "GARRAFA", "GORRO", "GRAMOFONE", "GRAMPO", "GUITARRA", "HALTERE", "HARPA", "IMPRESSORA", "INALADOR", "INCENSO", "INGRESSO", "ISCA", "JALECO", "JANELA", "JAQUETA", "KART", "KIT", "LÁPIS", "LEME", "LUVA", "LOUSA", "LIXO", "LUNETA", "LIQUIDIFICADOR", "LIVRO", "NAVE", "NAVIO", "NOTEBOOK", "ÓCULOS", "PENTE", "PIANO", "PICARETA", "PINÇA", "PISTOLA", "PLACA", "POTE", "QUADRO", "QUEPE", "RALO", "REDE", "SABONETE", "SACO", "TAMPA", "TECLADO", "TELEFONE", "UNIFORME", "UKULELE", "WALKMAN", "WEBCAM", "XADREZ", "XILOFONE", "ZABUMBA", "SOFÁ", "ARPÃO", "BAMBOLÊ", "BÚSSULA", "DIÁRIO", "DOMINÓ", "DIVÃ", "FICHÁRIO", "FOGÃO", "GIZ", "HELICÓPTERO", "HIDRÔMETRO", "ÍMÃ", "IOIÔ", "JERERÉ", "JOYSTICK", "LENÇOL", "LUMINÁRIA"];

objects.sort((a, b) => {
    return a.localeCompare(b);
});